### ISSUE TITLE
About this fork status.

### ISSUE THREAD

**Issue by Omicronrg9** [bcasiello/pixel-dungeon-rescue#10]
Hi, just stumbled upon this fork, it does seem interesting. I am writing you here because I would want to know if you havefinished or abandoned it.

Thanks in advance,
Ømicrón.

**Comment by bcasiello** [comment]
Hi, Ømicrón,
Not abandoned, just life became incredibly busy. I'd like to get back to it in a month or two, we'll see how it goes.

**Comment by Omicronrg9** [comment]
Glad to know it's not abandoned, in case you get some time and make some progress I'll be glad to play a run or two again! 

Kind regards,
Ømicrón.

**Comment by bcasiello** [comment]
1.0 is released! Give it a try if you're so inclined!

**Comment by Omicronrg9** [comment]
Nice! 
I briefly checked it (not much to test I guess, according to the changelog). Gonna try to finish a run soon if I get some time. Should I expect anything not explicitly put in the changelog?

And finally, do you have plans to further update it beyond fixing known bugs and things like that?

Kind regards,
Ømicrón.

**Comment by bcasiello** [comment]
I don't expect to change gameplay much if at all, this is mostly 'make Shattered a little less scary for the grandkids'. Still, I find a lot of your suggestions in the other issue intriguing - especially as they'd make the 'rescue' aspects more self-consistent.

If there's anything not in the changelog, it's because I forgot. :-)

I guess all I can say is don't expect a lot of changes in the short term, it'll be Shattered Jr. for a while yet and I can't guarantee it'll ever evolve beyond that.

**Comment by Omicronrg9** [comment]
Thank you for the quick reply. Of course whatever suits you will be fine. In any case, the changes I've stumbled upon are nice. The different coloured jellos is a nice detail, as well as the pizza, heh.

Kind regards,
Omicrón.
